#!/usr/bin/env python3
"""
Script to improve table formatting in generated LaTeX files.
This post-processes the complex table code generated by dblatex to make it cleaner and better formatted.
"""

import re
import sys

def simplify_table(tex_content):
    """
    Simplify overly complex table formatting in LaTeX content.
    """
    
    # Pattern to match the complex longtable structure generated by dblatex  
    # Look for the exact pattern we found
    complex_table_pattern = r'\{\\centering\\savetablecounter \\begingroup%.*?\\restoretablecounter%\s*\}'
    
    def replace_complex_table(match):
        table_content = match.group(0)
        
        # Extract all content between multicolumn entries - this captures table cell content
        # Use the working pattern from debugging
        cell_pattern = r'\\raggedright%\s*([^%}]+?)%?\s*\}'
        cells = re.findall(cell_pattern, table_content, re.DOTALL)
        
        if not cells:
            return table_content  # Return original if we can't parse
        
        # Clean up the cells and remove empty ones
        cleaned_cells = []
        for cell in cells:
            cell = cell.strip()
            # Remove extra LaTeX formatting 
            cell = re.sub(r'%\s*$', '', cell)
            cell = re.sub(r'\\textbf\{([^}]*)\}', r'\\textbf{\1}', cell)  # Clean up textbf
            if cell and cell not in ['', '%']:
                cleaned_cells.append(cell)
        
        if not cleaned_cells:
            return table_content  # Return original if no content found
            
        # Count columns by finding tabularnewline markers
        lines = table_content.split('\n')
        col_count = 3  # Default assumption
        
        for line in lines:
            if '\\tabularnewline' in line:
                # Count multicolumn entries in this line to determine column count
                multicolumn_count = line.count('\\multicolumn')
                if multicolumn_count > 0:
                    col_count = multicolumn_count
                    break
        
        # Group cells into rows
        rows = []
        for i in range(0, len(cleaned_cells), col_count):
            row = cleaned_cells[i:i + col_count]
            if len(row) == col_count:  # Only add complete rows
                rows.append(row)
        
        if not rows:
            return table_content  # Return original if no rows found
        
        # Build simplified table
        result = []
        result.append('\\begin{center}')
        result.append(f'\\begin{{tabular}}{{{"l" * col_count}}}')
        result.append('\\toprule')
        
        # Add rows
        for i, row in enumerate(rows):
            if i == 0:  # Header row
                # Don't double-bold if already bold
                formatted_row = []
                for cell in row:
                    if '\\textbf{' in cell:
                        formatted_row.append(cell)
                    else:
                        formatted_row.append(f'\\textbf{{{cell}}}')
                result.append(' & '.join(formatted_row) + ' \\\\')
                result.append('\\midrule')
            else:  # Data rows
                result.append(' & '.join(row) + ' \\\\')
        
        result.append('\\bottomrule')
        result.append('\\end{tabular}')
        result.append('\\end{center}')
        
        return '\n'.join(result)
    
    # Apply the transformation
    simplified = re.sub(complex_table_pattern, replace_complex_table, tex_content, flags=re.DOTALL)
    
    return simplified

def improve_table_formatting(input_file, output_file):
    """
    Read a LaTeX file, improve table formatting, and write the result.
    """
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        improved_content = simplify_table(content)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(improved_content)
        
        print(f"Table formatting improved. Output written to {output_file}")
        
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python improve_tables.py <input_file.tex> <output_file.tex>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    improve_table_formatting(input_file, output_file)